before_script:
  - echo "start package"
  - echo "setup java environment for Ubuntu 20.04"
  - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

deploy1:
  stage: build
  script:
    - mvn clean package
    - echo "copy to web directory"
    - cp target/my-toolbox-bin.zip /var/www/html/pkg/my-toolbox-bin.zip
